### ISSUE TITLE
RxSwift

### ISSUE THREAD

**Issue by aleksnied** [vanniktech/RxRiddles#10]
Hey, I'd love to port this to Swift. I think it's a great idea. The Rx world on iOS is much less documented so I feel we need to port some of this RxJava knowledge to our side ;) Would you be open to me doing that?

I could write a medium post linking yours etc. Or however else you'd like to be credited in my port.

**Comment by vanniktech** [comment]
Yeah sure. Feel free to port this over and mention the medium article / this project in any way possible.

**Comment by vanniktech** [comment]
Probably just stick to apache 2 and you're safe. (Not that I have any in depth knowledge about licensing).

**Comment by aleksnied** [comment]
Awesome, will do thanks!

**Comment by vanniktech** [comment]
Let me know once you've got something up
