### ISSUE TITLE
Question on Riddle #14

### ISSUE THREAD

**Issue by masteramyx** [vanniktech/RxRiddles#22]
This is not an "issue", just wanting some clarification. The riddle says 
`Retry the given [source] up to three times unless an [IllegalArgumentException] has been emitted`

However aren't we only "retrying" up to two times? We have an inital subscription, then comes the "retry" which happens twice. I was stuck on this because I kept setting `retry(3, Predicate())`.

**Comment by vanniktech** [comment]
Hmm wording might be improved. I meant that first time and then 2 more tries which will give you a total of three times.

Do you have a different wording in mind?

**Comment by masteramyx** [comment]
I think I'm being picky here but I would just say 
`Try the given [source] up to three times unless an [IllegalArgumentException] has been emitted` instead of `Retry...`

**Comment by vanniktech** [comment]
Sure. That sounds good. Want to submit a PR?

**Comment by masteramyx** [comment]
Sure thing. Thanks
