### ISSUE TITLE
Riddle 24 should return Single<Long>

### ISSUE THREAD

**Issue by tmtron** [vanniktech/RxRiddles#5]
Currently [Riddle24](../blob/master/src/main/kotlin/com/vanniktech/rxriddles/Riddle24.kt) returns `Single<Int>`. I think it should return `Single<Long>`, so that this solution works:
```
  fun solve(source: Observable<Any>): Single<Long> {
    return source.count()
  }
```
The current solution [Riddle24Solution](../blob/master/src/test/kotlin/com/vanniktech/rxriddles/solutions/Riddle24Solution.kt) works because the function does not specify a return-type.

**Comment by vanniktech** [comment]
Good catch!
